import type { GameData } from '../gameData/gameData';

/** CSS custom properties for the GUI root, from hud.json, so stylesheets and data can't disagree. */
export function guiTokens(data: GameData): Record<string, string> {
  const hud = data.hud.hud;
  const px = (n: number) => `${n}px`;
  const pct = (ratio: number) => `${ratio * 100}%`;
  return {
    '--gui-font': hud.font.fontFamily,
    '--gui-weight': hud.font.fontWeight,
    '--accent': hud.menuButton.fillColor,
    '--accent-hover': hud.menuButton.hoverColor,
    '--panel-margin': px(hud.panel.margin),
    '--panel-max-width': px(hud.panel.maxWidth),
    '--panel-back': hud.panel.backColor,
    '--panel-text': hud.panel.textColor,
    '--panel-detail': hud.panel.detailColor,
    '--panel-name-size': px(hud.panel.nameSize),
    '--panel-detail-size': px(hud.panel.detailSize),
    '--panel-gauge-height': px(hud.panel.gaugeHeight),
    '--gauge-back-color': hud.panel.gaugeBackColor,
    '--shatter-gate': hud.panel.shatterGateColor,
    '--redline': hud.panel.redlineColor,
    '--rev-name-size': px(hud.rev.nameSize),
    '--rev-multiplier-size': px(hud.rev.multiplierSize),
    '--rev-bar-height': px(hud.rev.barHeight),
    '--rev-pip-radius': px(hud.rev.pipRadius),
    '--rev-pip-gap': px(hud.rev.pipGap),
    '--rev-pop-seconds': `${hud.rev.rankUpSeconds}s`,
    '--pip-empty': hud.points.emptyColor,
    '--points-filled': hud.points.filledColor,
    '--points-pip-radius': px(hud.points.pipRadius),
    '--points-pip-gap': px(hud.points.pipGap),
    '--banner-size': px(hud.banner.fontSize),
    '--banner-small-size': px(hud.banner.smallFontSize),
    '--banner-y': pct(hud.banner.yRatio),
    '--banner-small-y': pct(hud.banner.smallYRatio),
    '--banner-stroke-color': hud.banner.strokeColor,
    '--banner-pop-seconds': `${hud.banner.popSeconds}s`,
    '--banner-pop-scale': String(hud.banner.popScale),
    '--shatter-prompt-size': px(hud.shatterPrompt.fontSize),
    '--shatter-prompt-color': hud.shatterPrompt.color,
    '--shatter-prompt-y': pct(hud.shatterPrompt.yRatio),
    '--pulse-seconds': `${1 / hud.shatterPrompt.pulsePerSecond}s`,
    '--hint-size': px(hud.hint.fontSize),
    '--hint-text': hud.hint.color,
    '--hint-bottom': px(hud.hint.bottomMargin),
    '--title-size': px(hud.screenLayout.titleSize),
    '--title-color': hud.screenLayout.titleColor,
    '--tagline-size': px(hud.screenLayout.taglineSize),
    '--tagline-color': hud.screenLayout.taglineColor,
    '--prompt-size': px(hud.screenLayout.promptSize),
    '--prompt-color': hud.screenLayout.promptColor,
    '--result-title-size': px(hud.screenLayout.resultTitleSize),
    '--backdrop-color': hud.screenLayout.backdropColor,
  };
}
